language: node_js
node_js:
- 13.8.0
cache:
  directories:
  - "~/.npm"
  - ".jest"
jobs:
  include:
  - stage: test
    if: commit_message !~ /(storybook-deploy)/
    script:
    - yarn eslint
    - yarn test --ci
    - yarn build
  - stage: deploy
    name: Bump version and release to npm
    if: branch = master AND (NOT type = pull_request) AND (commit_message !~ /(storybook-deploy)/)
    script:
    - yarn test:coveralls
    - yarn build
    - npx semantic-release
  - stage: deploy
    name: Deploy and release storybook
    if: branch = master AND (NOT type = pull_request) AND (commit_message =~ /(storybook-deploy)/)
    deploy:
      provider: heroku
      app: MW-Design
      on:
        repo: thousight/MW-Design
      api_key:
        secure: lXHpzTciaKXPi4KavBv1loGR+YwSNLSE8f1ROIBVyeArrGmyG8UzEKkt5he5IKJWY8ARCGSNf3/G9SACTpZS+1UlwEJRehZkro00acp7SM/kJdnuOoi8dIvxvMUFZayUS0hmArhefURdrB5JxSIvFTedewA5pgzsutL0+I7NgArMDo/Y8RcMiSpRmkwXPWPhmAlVarVZWeqjYw8xX3F6Xx1kJhNrnS4KhHRs9/AL3CrQrEziKhDMeT52D8i3SWwlOI1/KuZyHSZYvH4XK9RikclxqI2HZPZYh+vW0GE2o/QvKX94voZfF7ZCAupi8LrK9GVSxmYSScyElKYCDlN2yRjPoKBiilTEOH4w/Wt6b6YxiN5sbtN/bEU6PALRMf6KjlIVhujQqE9+YjjBc9LBwPed38+NX00B454NV+R1S6DIGh9T2Cgq5vObkvfJSbUI4UkT9ddvPHkc3D6wpIQxQInWI8uwS+/zX/yskuHvmQpGJvCWi6KPaWWs8puIDebZUg+qoZOZs19NjNbWl7M8bufh5oDIpzQVcmVdRAa2r7qnNpLsTY0SmeJXwwX4HuUAb3ylGRKQa2nnOKC2Asbc52pJ9UEE1FcpMFAS3BjSg94GPaqQuTRbuTUj+5Rat0I5o4cqN5VXJjHzqSVyGkClWqhJaRU8TLHmUcOmLlRMljU=
