language: node_js
node_js:
  - "13.8.0"
cache:
  directories:
    - ~/.npm
    - .jest
jobs:
  include:
    - stage: "Test"
      if: commit_message !~ /(storybook-deploy)/
      script:
        - yarn eslint
        - yarn test --ci
        - yarn build
    - stage: "Bump version and release to npm"
      if: branch = master AND (NOT type = pull_request) AND  AND (commit_message !~ /(storybook-deploy)/)
      script:
        - yarn test:coveralls
        - yarn build
        - npx semantic-release
    - stage: "Deploy and release storybook"
        if: branch = master AND (NOT type = pull_request) AND (commit_message =~ /(storybook-deploy)/)
        script:
          - yarn test --ci