export const  THEME_TOKEN_BACKGROUND = "--mwds-background"
export const  THEME_TOKEN_TEXT = "--mwds-text"
export const  THEME_TOKEN_PRIMARY = "--mwds-primary"
export const  THEME_TOKEN_SECONDARY = "--mwds-secondary"
export const  THEME_TOKEN_ACCENT = "--mwds-accent"
